spring:
  application:
    name: percentage
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  level:
    root: INFO
    org:
      mockserver:
        log:
          MockServerEventLog: ERROR

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true


percentage:
  baseUrl: http://localhost:8081

